### ISSUE TITLE
Allow a silent mode config setting

### ISSUE THREAD

**Issue by skellock** [infinitered/gluegun#52]
Inside the app `.toml` file, let's add:

```toml
[defaults]
silent = true
```

When true (default is false), it will suppress all print commands triggered through the print extension.
